name: 'Saludar al creador del Issue'
description: 'Responde automáticamente con un saludo al usuario que abre un issue'
author: 'raulmaciasdev'
inputs:
  github-token:
    description: 'Token automático de GitHub para interactuar con la API'
    required: true
runs:
  using: 'node24'
  main: 'dist/index.js'

# ─── CONFIGURACIÓN DE BRANDING ───
branding:
  icon: 'terminal'
  color: 'green'