name: Recordatorio Horario

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  # Añadimos el activador externo
  repository_dispatch:
    types: [activacion_manual_externa]

jobs:
  reporte-horario:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar herramientas de información
        run: |
          sudo apt-get update
          sudo apt-get install -y neofetch

      - name: Ejecutar script de saludo y Neofetch
        run: |
          echo "¡Hola! Este flujo ha sido activado."
          echo "La hora actual en el servidor es: $(date)"
          echo "--------------------------------------------------"
          neofetch --off
          echo "--------------------------------------------------"
          echo "Versión de Node.js:"
          node -v
          
      # PASO EXTRA: Leer datos enviados desde fuera (Opcional)
      - name: Mostrar datos personalizados enviados en la petición
        run: |
          echo "Mensaje recibido: ${{ github.event.client_payload.mensaje }}"
          echo "Enviado por: ${{ github.event.client_payload.usuario }}"
